version: 2
project_name: protokit

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
